version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ecart-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: ecart-redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: ecart-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

volumes:
  mongo-data:
